// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeq2jNktWOPY_ReaC9l8lpHPKgxZGoWeY',
    appId: '1:983086369462:web:f00e2d94cebca0cae7b417',
    messagingSenderId: '983086369462',
    projectId: 'snap-stock',
    authDomain: 'snap-stock.firebaseapp.com',
    storageBucket: 'snap-stock.appspot.com',
    measurementId: 'G-4SRP210CFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbILp4h-thLGuiU32LgCVzDszJaGMI5lE',
    appId: '1:983086369462:android:b73d861f459da7c6e7b417',
    messagingSenderId: '983086369462',
    projectId: 'snap-stock',
    storageBucket: 'snap-stock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAKqPUDqGaBnmBgVKOYKBpFgXFWyeLHK8',
    appId: '1:983086369462:ios:010b6589acf7ebc1e7b417',
    messagingSenderId: '983086369462',
    projectId: 'snap-stock',
    storageBucket: 'snap-stock.appspot.com',
    iosClientId:
        '983086369462-93nsiute3c2fjndgqtouln4oesm0laut.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
